version: "3"
services:
  hr-mongodb:
    image: mongo:latest
    container_name: hr-mongodb
    ports:
      - '27017:27017'
      
  springboot-mongo-app:
    container_name: springboot-mongodb
    image: springboot-mongo-app:1.0.0
    ports:
      - '8001:8007'